### ISSUE TITLE
Overcoming the Need for TSConfig Multiple Inheritance

### ISSUE THREAD

**Issue by johncmunson** [NiGhTTraX/ts-monorepo#195]
I wrote up a [lengthy discussion of this](https://github.com/microsoft/TypeScript/issues/42386#issuecomment-1019296269) over on the Typescript github issue for multiple inheritance, but I referenced this project because this is where I first encountered it.

@NiGhTTraX I'm curious if this is something that you have investigated before? With TS not directly supporting multiple inheritance in the tsconfig files, have you come up with any alternative solutions? Or, has this just not been a real issue for you yet?

**Comment by NiGhTTraX** [comment]
Hey @johncmunson, good question! This project actually contains an example of what you're describing — the [`components` package](https://github.com/NiGhTTraX/ts-monorepo/tree/06eece11c8934163d8b64433e0da6d0f4c988b47/packages/components) has to set `jsx: true` in both the [IDE config](https://github.com/NiGhTTraX/ts-monorepo/blob/06eece11c8934163d8b64433e0da6d0f4c988b47/packages/components/tsconfig.json#L4) and the [build config](https://github.com/NiGhTTraX/ts-monorepo/blob/06eece11c8934163d8b64433e0da6d0f4c988b47/packages/components/tsconfig.build.json#L6). The other packages don't need it, so that's why it's not hoisted in the root config. It would definitely be nice to have multiple inheritance, so I could set that in a single config and then inherit it, along with the monorepo config that holds the path aliases.

At the end of the day, tsconfigs don't change that often, so a bit of duplication doesn't hurt IMO. Multiple inheritance would be an elegant solution, so let's hope the TS team will implement it at some point, seeing as monorepos are becoming more common.

**Comment by johncmunson** [comment]
Oh cool, thanks for pointing that out! I basically arrived at the same solution as you did as I was pondering this earlier today. However, instead of having my IDE configs at the workspace level extend from the root level IDE config, I decided to have them extend from the sibling build config, and then I duplicated the path aliases everywhere.

Either way involves a bit of duplication, but you're right, it's not really a big deal since the files rarely change.

In addition to multiple inheritance, I've also seen people request support for `tsconfig.js` or `tsconfig.ts` files, which would also help out in this scenario.

**Comment by johncmunson** [comment]
https://github.com/microsoft/TypeScript/pull/50403

**Comment by NiGhTTraX** [comment]
Thanks for the reminder @johncmunson! Before I use the new multiple inheritance feature to remove some duplication in the tsconfigs, I will:

1. Let the tooling ecosystem adapt to the new version. #308 shows some dependencies that need to accept 5.0 in their peer dependencies.
2. Give everyone some time to hop onto the new version. People might clone this repo and then downgrade the TS version to match what they're using in their project only to find out that it breaks everything because of the multiple inheritance.
