### ISSUE TITLE
Add example for sub module exports

### ISSUE THREAD

**Issue by sean256** [NiGhTTraX/ts-monorepo#219]
Using the same structure as the foo & bar example, but add a sub export to foo.

```
- packages
  - bar
    - src
      - index.ts
  - foo
    - src
      - index.ts
        - sub-export
          - index.ts
```

I think showing how to get sub exports working would be a great addition

`/packages/foo/src/sub-export/index.ts`
```
export const meaningOfASubExport = 'Niiiiice';
```

`/packages/bar/src/index.ts`
```
import { meaningOfASubExport } from "@nighttrax/foo/sub-export";

// eslint-disable-next-line no-console
console.log(meaningOfASubExport);
```

**Comment by NiGhTTraX** [comment]
Hey @sean256, thanks for your suggestion. Unfortunately, it's not a trivial thing to add to this template since there's no good way to make it work in all cases.

If you have "bundled" apps (like the ones in [`examples/*`](https://github.com/NiGhTTraX/ts-monorepo#frameworks-and-tools-integrations)), then you can simply add more path aliases in the config (see the [CRA example](https://github.com/NiGhTTraX/ts-monorepo/blob/32ef2ac9a0eaf38c9478022abab7389a8791148c/examples/cra/tsconfig.paths.json#L6)). For your case above, depending on which `tsconfig.json` you add it in, it would look something like this:

```json
"@nighttrax/foo/*": ["./packages/foo/src/*"]
```

That will just work :tm: and enable `import @nighttrax/foo/sub-export` from the CRA package for instance. However, that import will result in a broken build for the `bar` package, because `bar` is meant to be published to npm, where consumers won't have the path aliases set up, so they have to find that export inside `node_modules/bar`. Because `bar` only defines [`package.json#main`](https://github.com/NiGhTTraX/ts-monorepo/blob/32ef2ac9a0eaf38c9478022abab7389a8791148c/packages/bar/package.json#L4), Node or TS will not find the file.

Node@12+ introduced [subpath exports](https://nodejs.org/api/packages.html#subpath-exports) via `package.json#exports`, but they're still not supported by TypeScript (see https://github.com/microsoft/TypeScript/issues/46452).
