### ISSUE TITLE
Support for using alias paths in the package

### ISSUE THREAD

**Issue by syhxzzz** [NiGhTTraX/ts-monorepo#348]
Hi, sorry to bother you again.

I have been using your solution to build my project and encountered a challenge that I need some assistance with. Specifically, I am trying to create alias paths in a package shared by multiple apps.

I reviewed your `apps/cra` folder and noticed the [`@hooks/` alias example](https://github.com/NiGhTTraX/ts-monorepo/blob/f9c8380e30a5c3bae8cd82b3a7b72d001aba19b1/apps/cra/tsconfig.paths.json#L10). However, this approach did not work for me, as the alias paths are located in the apps folder. I searched through the issues using the keyword **alias** but could not find a solution that addresses my problem.

I attempted to modify the tsconfig.json file in the package/foo example to include an alias path, and while the IDE did not raise any alerts, the alias paths were not recognized by webpack during packaging. To resolve this, I had to add the alias @foo/ to the apps/webpack/tsconfig.json file.
<img width="645" alt="image" src="https://github.com/user-attachments/assets/5568b54a-fb4c-4fc6-b629-92e8adbd1418">
<img width="792" alt="image" src="https://github.com/user-attachments/assets/1029113a-6400-4e5e-b11e-f98523655050">

Here is the change I made: [Commit Link](https://github.com/syhxzzz/ts-monorepo/commit/26943eed45e82d415896ccf30e7ad04d26f4684f).

I am wondering if there is a better way to create alias paths in the package folder. It feels unusual to write alias paths in the apps' tsconfig.json, but I am unsure of a better approach.

Thank you for your time.

Best regards

**Comment by NiGhTTraX** [comment]
You're on the right path. If you want to use aliases within a package then you need to configure those aliases for all its consumers as well. Either you do it per package like in the commit you linked, or you centralize them in the monorepo root.

The above is necessary if you want "live types" e.g. Go to definition and type errors work as expected without first having to build the projects. If you're fine with building [some] packages first, then you can define the aliases just once and then use a toolchain that rewrites those aliases when building e.g. webpack.

For me, the possibility of not getting the intended outcome because I forgot to build some package first outweighs the alternative of some duplication in the configs.
