### ISSUE TITLE
Running wrong tests in the CRA example?

### ISSUE THREAD

**Issue by henriqueweiand** [NiGhTTraX/ts-monorepo#41]
I am testing some changes to the examples and I noticed that to run the tests on the CRA project it seems to me to be incorrect.

Was that so?

https://github.com/NiGhTTraX/ts-monorepo/blob/54681cf11109393ae2a4af84e24a7ff6108287af/examples/cra/package.json#L24

**Comment by henriqueweiand** [comment]
Still on the tests, now notice that the examples in the vast majority are like this. What would be the recommended recommendation to run the tests on the monorepo? I mean, is it ideal for each project to have its own jest configuration for example?

**Comment by NiGhTTraX** [comment]
Hi @henriqueweiand! The `test` script for each package in this monorepo is meant to build that respective package so that I can be sure the monorepo is setup correctly, it's not meant to be an example of how to run "real" tests.

> is it ideal for each project to have its own jest configuration for example?

You could have each package have its own script that runs `jest`, or have one in the root that runs the tests for all the packages. Having one per package would make it slightly easier to test only that package, and makes it a bit more self contained.

There's no right or wrong really, so choose what makes most sense to you :)

**Comment by henriqueweiand** [comment]
thanks! I exclaimed well
