### ISSUE TITLE
nextJS has "external dir" feature

### ISSUE THREAD

**Issue by Goldziher** [NiGhTTraX/ts-monorepo#57]
Hi there,

Regarding nextJS, Instead of doing this:

```javeascript
    webpack: (config) => {
        const tsRule = config.module.rules.find(
            (rule) => rule.test && rule.test.toString().includes("tsx|ts")
        );
        console.log(tsRule)
        tsRule.include = undefined;
        tsRule.exclude = /node_modules/;

        return config;
    },
```

You can do this:

```
    experimental: {
        externalDir: true,
    },
```

**Comment by NiGhTTraX** [comment]
Very nice, thanks for sharing this @Goldziher! It seems like the flag is doing exactly what the config is doing (removing/not setting the `include` option).

Since this is an experimental feature, and requires Next >= 10.1.0, I've added a mention in the docs about the alternative and kept the current example that should work for most people.
