### ISSUE TITLE
ESLint not working

### ISSUE THREAD

**Issue by ramandhingra** [NiGhTTraX/ts-monorepo#84]
Hello @NiGhTTraX 

In the root package.json, there exists a devDependency named eslint. eslint-plugin-import is another dependency.
Also there is a "yarn lint" command in the same package.json.

In the examples/nestjs/package.json, eslint devDependency is again there.

In the examples/cra/package.json, there are no eslint-related dependencies. Also, the eslintConfig property is not there.

Earlier the eslint was working for nestjs as soon as I used to start the VSCode. Then I replaced 'react-app-rewired' with 'craco' in the CRA.. to provide support for tailwindcss.

Now the ESLint is neither working for nestjs nor cra. Why is there a mismatch between the esling configurations for the cra and nestjs examples?

Kindly help. Thanks

**Comment by NiGhTTraX** [comment]
Hi @ramandhingra, thanks for bringing it to my attention that ESLint was a dev dependency in the NestJS project. I've removed it in bb9091456e6dfeafac4d147803897d9800bfbe49 since I only intended ESLint to be run from the root for all projects at once (this is not to say that you couldn't run it per project).

I'm not sure why using craco instead of rewired would cause ESLint to stop working. Can you try again with the latest master to see if it's working after removing the duplicate dependency? If not, could you provide an error message or some logs showing the problem?

**Comment by ramandhingra** [comment]
I removed the eslint dependency from nestjs.. but it did not work.

I then noticed that the .eslintrc.js and .eslintignore were missing in the root folder. I added these files and it is working now.

Thanks. This package is really wonderful.

**Comment by ramandhingra** [comment]
I have another question. Could you pl. answer. Running yarn install in the root creates the node_modules directory in the root. Good enough. But why does it create the node_modules folders inside the examples (nestjs and cra) directories? These folders have only few sub-folders in them though.

I had a look at the contents of these node_module folders. They basically comprise the JS files while the corresponding root modules folder has the TS files.

Is there any way to get rid of the modules folders created inside the nestjs and cra?

**Comment by NiGhTTraX** [comment]
That's how workspaces work: yarn/npm 7 will try to put as many dependencies in the root `node_modules` as possible, while putting the specific ones that only some packages need closer to them. The symlinks between the workspaces are set up in the root so that every package can find them.

There's nothing you need to be concerned about, nor should you try to remove anything.
